site_name: "European Environment for Scientific Software Installations (EESSI)"
site_url: https://eessi.github.io/docs/
extra:
  analytics:
    provider: google
    property: UA-169665333-1
theme:
  name: material
  features:
    - instant
    - content.code.annotate
  logo: img/logos/EESSI.png
  favicon: img/logos/EESSI.png
repo_name: EESSI @ GitHub
repo_url: https://github.com/EESSI
edit_uri: docs/edit/main/docs
nav:
  - Home: index.md
  - Design:
    - Project overview: overview.md
    - Filesystem layer: filesystem_layer.md
    - Compatibility layer: compatibility_layer.md
    - Software layer: software_layer.md
    - Supported CPU targets: software_layer/cpu_targets.md
  - Available software and repositories:
      - Software: available_software/overview.md
      - Repositories:
        - Production: repositories/software.eessi.io.md
        - RISC-V: repositories/riscv.eessi.io.md
        - Pilot: repositories/pilot.md
        - Development repository: repositories/dev.eessi.io.md
  - Installation and configuration:
    - Is EESSI already installed?: getting_access/is_eessi_accessible.md
    - Native: getting_access/native_installation.md
    - Container: getting_access/eessi_container.md
    - Windows and macOS:
      - Windows with WSL: getting_access/eessi_wsl.md
      - macOS with Lima: getting_access/eessi_limactl.md
    - Configuring EESSI:
      - How to configure EESSI: site_specific_config/host_injections.md
      - GPU support: site_specific_config/gpu.md
      - Custom LMOD hooks: site_specific_config/lmod_hooks.md
  - Basic usage:
    - Set up environment: using_eessi/setting_up_environment.md
    - Basic commands: using_eessi/basic_commands.md
    - Demos: using_eessi/eessi_demos.md
  - Advanced usage:
    - Setting up your Stratum: filesystem_layer/stratum1.md
    - Building software with EESSI: using_eessi/building_on_eessi.md
    - Test suite:
      - Overview: test-suite/index.md
      - Installation & configuration: test-suite/installation-configuration.md
      - ReFrame configuration file: test-suite/ReFrame-configuration-file.md
      - Usage: test-suite/usage.md
      - Available tests: test-suite/available-tests.md
      - Writing tests: test-suite/writing-portable-tests.md
      - Release notes: test-suite/release-notes.md
      - API documentation: testsuite_api/
    - Known issues and workarounds:
      - v2023.06: known_issues/eessi-2023.06.md
  - Adding software to EESSI: 
    - Overview: adding_software/overview.md
    - For contributors:
      - Contribution policy: adding_software/contribution_policy.md
      - Open PR: adding_software/opening_pr.md
      - Debugging: adding_software/debugging_failed_builds.md
      - Development repository: adding_software/adding_development_software.md
    - For maintainers:
      - BTD bot: bot.md
      - Building software: adding_software/building_software.md
      - Deploying software: adding_software/deploying_software.md
      - Build nodes: software_layer/build_nodes.md
  - Community and support:
    - Getting support: support.md
    - Meetings: meetings.md
    - Talks: talks.md
        # - Community meeting (Sept'22): meetings/2022-09-amsterdam.md
    - Contact info: contact.md
  - Training: training/index.md
  - Systems where EESSI is available: systems.md
  - Governance: governance.md
  - Blog: blog/index.md
plugins:
  - blog:
      blog_toc: true
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
  # Enable macros so we can use global variables
  - macros
  - redirects:
      redirect_maps:
        adding_software.md: adding_software/overview.md
        contributing_sw/building_software.md: adding_software/building_software.md
        contributing_sw/contribution_policy.md: adding_software/contribution_policy.md
        contributing_sw/debugging_failed_builds.md: adding_software/debugging_failed_builds.md
        contributing_sw/deploying_software.md: adding_software/deploying_software.md
        contributing_sw/opening_pr.md: adding_software/opening_pr.md
        contributing_sw/overview.md: adding_software/overview.md
        software_layer/adding_software.md: adding_software/overview.md
        pilot.md: repositories/pilot.md
        gpu.md: site_specific_config/gpu.md
  # Enable our custom plugin for json-ld metadata
  - inject_ld_json
    # link to any Markdown heading
  - autorefs
    # api automatics documentation 
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/test-suite] 
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            show_source: false
  - gen-files:
      scripts:
          - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - section-index
markdown_extensions:
  # enable adding HTML attributes and CSS classes
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  # support for using MarkDown in HTML
  - md_in_html
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # line numbers
  - pymdownx.highlight:
      anchor_linenums: true
  # syntax highlighting for inline code
  - pymdownx.inlinehilite
  # embed content from arbitrary files
  - pymdownx.snippets
  # tabbed contents
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # clickable details
  - pymdownx.details
  - toc:
      permalink: true
  # emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  # add links in bottom right
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eessi_hpc
  # this gets auto-updated via update_generated_time.sh script run in update_available_software.yml action
  generated_time: "Sat, 26 Apr 2025 at 01:46:16 UTC"
extra_javascript:
  # mermaid diagram
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
  # javascript which generates overview of available software
  - https://code.jquery.com/jquery-3.7.0.min.js
  - https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js
  - available_software/javascripts/populate_overview.js
  - https://cdn.datatables.net/plug-ins/2.2.2/pagination/bootstrap_input.js
extra_css:
  # CSS for popultate_overview
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css
  - available_software/css/style_table.css
  - https://cdn.datatables.net/2.2.2/css/dataTables.semanticui.css
