site_name: "European Environment for Scientific Software Installations (EESSI)"
site_url: https://eessi.github.io/docs/
extra:
  analytics:
    provider: google
    property: UA-169665333-1
theme:
  name: material
  features:
    - instant
    - content.code.annotate
  logo: img/logos/EESSI.png
  favicon: img/logos/EESSI.png
repo_name: EESSI @ GitHub
repo_url: https://github.com/EESSI
edit_uri: docs/edit/main/docs
nav:
  - Home: index.md
  - Design:
    - Project overview: overview.md
    - Filesystem layer: filesystem_layer.md
    - Compatibility layer: compatibility_layer.md
    - Software layer: software_layer.md
    - Supported CPU targets: software_layer/cpu_targets.md
    - Supported GPU targets: software_layer/gpu_targets.md
  - Available software: available_software/index.md
  - Repositories:
    - Production:
      - Software: repositories/software.eessi.io.md
      - Versions: repositories/versions.md
    - RISC-V: repositories/riscv.eessi.io.md
    - Development repository: repositories/dev.eessi.io.md
  - Installation and configuration:
    - Is EESSI already installed?: getting_access/is_eessi_accessible.md
    - Native: getting_access/native_installation.md
    - Container: getting_access/eessi_container.md
    - Windows and macOS:
      - Windows with WSL: getting_access/eessi_wsl.md
      - macOS with Lima: getting_access/eessi_limactl.md
    - Configuring EESSI:
      - How to configure EESSI: site_specific_config/host_injections.md
      - GPU support: site_specific_config/gpu.md
      - Custom LMOD hooks: site_specific_config/lmod_hooks.md
  - Basic usage:
    - Set up environment: using_eessi/setting_up_environment.md
    - Basic commands: using_eessi/basic_commands.md
    - Demos: using_eessi/eessi_demos.md
    - EESSI in CI: using_eessi/eessi_in_ci.md
  - Advanced usage:
    - Setting up your Stratum: filesystem_layer/stratum1.md
    - Building software with EESSI: using_eessi/building_on_eessi.md
    - Test suite:
      - Overview: test-suite/index.md
      - Installation & configuration: test-suite/installation-configuration.md
      - ReFrame configuration file: test-suite/ReFrame-configuration-file.md
      - Usage: test-suite/usage.md
      - Available tests: test-suite/available-tests.md
      - Writing tests: test-suite/writing-portable-tests.md
      - Release notes: test-suite/release-notes.md
      - API documentation: testsuite_api/
      # - Dashboard: test-suite/dashboard.md
    - Known issues and workarounds:
      - v2023.06: known_issues/eessi-2023.06.md
  - Adding software to EESSI: 
    - Overview: adding_software/overview.md
    - For contributors:
      - Contribution policy: adding_software/contribution_policy.md
      - Open PR: adding_software/opening_pr.md
      - Debugging: adding_software/debugging_failed_builds.md
      - Development repository: adding_software/adding_development_software.md
    - For maintainers:
      - BTD bot: bot.md
      - Building software: adding_software/building_software.md
      - Deploying software: adding_software/deploying_software.md
      - Build nodes: software_layer/build_nodes.md
  - Community and support:
    - Getting support: support.md
    - Meetings: meetings.md
    - Talks: talks.md
        # - Community meeting (Sept'22): meetings/2022-09-amsterdam.md
    - Contact info: contact.md
  - Training & events: training-events/index.md
  - Systems where EESSI is available: systems.md
  - Governance:
    - Overview: governance/index.md
    - Charter: governance/charter.md
    - Governance: governance/governance.md
    - Policies: governance/policies.md
    - Code of Conduct: governance/code_of_conduct.md
    - Terms of Use: governance/terms_of_use.md
    - Current Steering Committee: governance/steering_committee.md
  - Blog: blog/index.md
plugins:
  - blog:
      blog_toc: true
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
  # Enable macros so we can use global variables, and use Jinja2 templates
  # see also https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/
  - macros:
      module_name: docs/available_software/macros
  - redirects:
      redirect_maps:
        # useful easy-to-remember short URLs, don't remove these!
        gpu.md: site_specific_config/gpu.md
        rocm.md: site_specific_config/rocm.md
        # redirects for pages that were moved at some point
        adding_software.md: adding_software/overview.md
        contributing_sw/building_software.md: adding_software/building_software.md
        contributing_sw/contribution_policy.md: adding_software/contribution_policy.md
        contributing_sw/debugging_failed_builds.md: adding_software/debugging_failed_builds.md
        contributing_sw/deploying_software.md: adding_software/deploying_software.md
        contributing_sw/opening_pr.md: adding_software/opening_pr.md
        contributing_sw/overview.md: adding_software/overview.md
        software_layer/adding_software.md: adding_software/overview.md
        pilot.md: repositories/pilot.md # https://www.eessi.io/docs/pilot is mentioned in the EESSI open access paper
        available_software/overview.md: available_software/index.md
        # training/ was renamed to training-events/ + <year> subdirectory was removed for Happy Hour sessions
        training/index.md: training-events/index.md
        training/happy-hours-sessions.md: training-events/happy-hours-sessions.md
        training/2025/happy-hours-sessions.md: training-events/happy-hours-sessions.md
        training/2025/hackathon-eurohpc-user-days.md: training-events/2025/hackathon-eurohpc-user-days.md
        training/2026/happy-hours-sessions.md: training-events/happy-hours-sessions.md
        training/2025/webinar-series-2025Q2.md: training-events/2025/webinar-series-2025Q2.md
        training-events/2025/happy-hours-sessions.md: training-events/happy-hours-sessions.md
        training-events/2026/happy-hours-sessions.md: training-events/happy-hours-sessions.md
        # tutorial site for EESSI webinar on CernVM-FS (May 2025)
        tutorial/index.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/index.md
        tutorial/eessi/using-eessi.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/using-eessi.md
        tutorial/eessi/high-level-design.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/high-level-design.md
        tutorial/eessi/what-is-eessi.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/what-is-eessi.md
        tutorial/eessi/support.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/support.md
        tutorial/eessi/inspiration.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/inspiration.md
        tutorial/eessi/index.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/index.md
        tutorial/eessi/motivation-goals.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/eessi/motivation-goals.md
        tutorial/appendix/terminology.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/appendix/terminology.md
        tutorial/access/alternatives.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/access/alternatives.md
        tutorial/access/stratum1.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/access/stratum1.md
        tutorial/access/index.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/access/index.md
        tutorial/access/proxy.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/access/proxy.md
        tutorial/access/client.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/access/client.md
        tutorial/troubleshooting.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/troubleshooting.md
        tutorial/performance.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/performance.md
        tutorial/cvmfs/technical-details.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/cvmfs/technical-details.md
        tutorial/cvmfs/what-is-cvmfs.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/cvmfs/what-is-cvmfs.md
        tutorial/cvmfs/flagship-repositories.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/cvmfs/flagship-repositories.md
        tutorial/containers.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/containers.md
        tutorial/monitoring.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/monitoring.md
        tutorial/configuration_hpc.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/configuration_hpc.md
        tutorial/creating-repo.md: training-events/2025/tutorial-best-practices-cvmfs-hpc/creating-repo.md
  # Enable our custom plugin for json-ld metadata
  - inject_ld_json
    # link to any Markdown heading
  - autorefs
    # api automatics documentation 
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [test-suite/test-suite] 
          options:
            docstring_style: sphinx
            docstring_section_style: spacy
            show_source: false
  - gen-files:
      scripts:
          - docs/generate_eessi_testsuite_api_docs.py
  - literate-nav:
      nav_file: summary.md
  - section-index
markdown_extensions:
  # enable adding HTML attributes and CSS classes
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  # support for using MarkDown in HTML
  - md_in_html
  # support for footnotes
  - footnotes
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # line numbers
  - pymdownx.highlight:
      anchor_linenums: true
  # syntax highlighting for inline code
  - pymdownx.inlinehilite
  # embed content from arbitrary files
  - pymdownx.snippets
  # tabbed contents
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # clickable details
  - pymdownx.details
  - toc:
      permalink: true
  # emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  # add links in bottom right
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eessi_hpc
  # this gets auto-updated via update_generated_time.sh script run in update_available_software.yml action
  generated_time: "Fri, 06 Feb 2026 at 13:12:13 UTC"
  slack_invite_url: "https://join.slack.com/t/eessi-hpc/shared_invite/zt-2wg10p26d-m_CnRB89xQq3zk9qxf1k3g"
extra_javascript:
  # mermaid diagram
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
  # javascript used in overview of available software
  - available_software/javascripts/software-filter.js
extra_css:
  # CSS for popultate_overview
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css
  - available_software/css/software.css
  - https://cdn.datatables.net/2.2.2/css/dataTables.semanticui.cssoftwares
