site_name: "European Environment for Scientific Software Installations (EESSI)"
site_url: https://eessi.github.io/docs/
extra:
  analytics:
    provider: google
    property: UA-169665333-1
theme:
  name: material
  features:
    - instant
    - content.code.annotate
  logo: img/logos/EESSI.png
  favicon: img/logos/EESSI.png
repo_name: EESSI @ GitHub
repo_url: https://github.com/EESSI
edit_uri: docs/edit/main/docs
nav:
  - Home: index.md
  - Project overview: overview.md
  - Filesystem layer: 
    - Overview: filesystem_layer.md
    - filesystem_layer/stratum1.md
  - Compatibility layer: compatibility_layer.md
  - Software layer:
    - Overview: software_layer.md
    - software_layer/cpu_targets.md
    - software_layer/build_nodes.md
  - Test suite:
    - Overview: test-suite/index.md
    - Installation & configuration: test-suite/installation-configuration.md
    - Usage: test-suite/usage.md
    - Release notes: test-suite/release-notes.md
  - Build-test-deploy bot: bot.md
  - Repositories:
    - EESSI repository: repositories/software.eessi.io.md
    - Pilot repository: repositories/pilot.md
  - Getting access to EESSI:
    - getting_access/is_eessi_accessible.md
    - getting_access/native_installation.md
    - getting_access/eessi_container.md
  - Using EESSI:
    - using_eessi/setting_up_environment.md
    - using_eessi/basic_commands.md
    - using_eessi/building_on_eessi.md
    - using_eessi/eessi_demos.md
  - Adding software to EESSI:
    - Overview: adding_software/overview.md
    - adding_software/contribution_policy.md
    - adding_software/opening_pr.md
    - adding_software/building_software.md
    - adding_software/debugging_failed_builds.md
    - adding_software/deploying_software.md
  # Todo: write on how to contribute to the EESSI test suite
  # - Contributing software tests to the EESSI test suite:
  - GPU support: gpu.md
  - Getting support: support.md
  - Meetings:
      - Overview: meetings.md
      - Community meeting (Sept'22): meetings/2022-09-amsterdam.md
  - Talks: talks.md
  - Contact info: contact.md
plugins:
  # show revision date at bottom of each page
  - git-revision-date-localized
  # necessary for search to work
  - search
  - redirects:
      redirect_maps:
        adding_software.md: adding_software/overview.md
        contributing_sw/building_software.md: adding_software/building_software.md
        contributing_sw/contribution_policy.md: adding_software/contribution_policy.md
        contributing_sw/debugging_failed_builds.md: adding_software/debugging_failed_builds.md
        contributing_sw/deploying_software.md: adding_software/deploying_software.md
        contributing_sw/opening_pr.md: adding_software/opening_pr.md
        contributing_sw/overview.md: adding_software/overview.md
        software_layer/adding_software.md: adding_software/overview.md
        pilot.md: repositories/pilot.md
markdown_extensions:
  # enable adding HTML attributes and CSS classes
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  # line numbers
  - pymdownx.highlight:
      anchor_linenums: true
  # syntax highlighting for inline code
  - pymdownx.inlinehilite
  # embed content from arbitrary files
  - pymdownx.snippets
  # tabbed contents
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # clickable details
  - pymdownx.details
  - toc:
      permalink: true
  # emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  # add links in bottom right
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eessi_hpc
